### ISSUE TITLE
Warnings and Errors aren't shown inline

### ISSUE THREAD

**Issue by darthdeus** [chaika2013/ide-haskell#32]
I'm not sure if I'm doing something wrong, but I've setup my paths to ghc-mod and stylish-haskell, and it seems that the typechecking works, but it doesn't display it inline

![](http://i.imgur.com/gN0DSMA.png)

**Comment by lierdakil** [comment]
Since ide-haskell have not been updated to work with latest API changes, you need to either disable Shadow DOM in your editor settings, patch stylesheet (deprecation cop shows where exactly and gives hints on what to change -- specifically, you want to change .editor to atom-text-editor::shadow), or use another tool providing similar functions (see, e.g. [haskell-ghc-mod][1])
![image](https://cloud.githubusercontent.com/assets/7275622/5902509/28a744ec-a58c-11e4-84be-4aa4d7c08d6e.png)
[1]: https://atom.io/packages/haskell-ghc-mod

**Comment by lierdakil** [comment]
I deployed 0.3.1, which should fix this issue. Could you test and confirm that this is indeed the case on your end?

**Comment by jmquigs** [comment]
Note, you probably need to turn _on_ shadow dom to see the inline markers with 0.3.1.

**Comment by lierdakil** [comment]
So... I'm closing it for now, since it should work now. Feel free to open new bugs if problem persists.

**Comment by jmquigs** [comment]
@lierdakil, I do know of one case where there is a problem with the markers.  Occasionally the query for the .gutter object doesn't return anything, thus, the mouse-over events cannot be attached to the markers.  The effect is that the markers are visible, but if you mouse over them, no tooltip appears.  I have not yet delved into this to see what is going on...its not quite this bug though, so we can probably leave this closed.

**Comment by lierdakil** [comment]
@jmquigs, huh, interesting. `div.gutter` should always be present unless hidden (and then there shouldn't be any tooltips, obviously). `div.line-number` is entirely different story though, but I don't think that's used in ide-haskell. Anyway, this is unrelated, so I'm keeping it closed.
